language: java

os:
  - linux
  - osx

before_script:
  - cd $TRAVIS_BUILD_DIR
  - curl -fsSL# https://deno.land/x/install/install.sh | DENO_INSTALL=$TRAVIS_BUILD_DIR sh
  - curl -fsSL# https://denopkg.com/chiefbiiko/dynamodb/start_db.sh | bash

script:
  - ACCESS_KEY_ID=fraud SECRET_ACCESS_KEY=fraud $TRAVIS_BUILD_DIR/deno run --allow-read=$(pwd) --allow-env --allow-net ./test.ts